# Generated by Django 2.0.3 on 2018-04-01 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cidade', '0001_initial'),
        ('Rota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cidade.Cidade'),
        ),
    ]
