# Generated by Django 2.0.4 on 2018-04-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ponto', '0001_initial'),
        ('Rota', '0002_rota_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='pontos',
            field=models.ManyToManyField(to='Ponto.Ponto'),
        ),
    ]
