# Generated by Django 2.0.4 on 2018-04-29 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0001_initial'),
        ('Rota', '0003_rota_pontos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='cidade',
        ),
        migrations.AddField(
            model_name='rota',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Categoria.Categoria'),
        ),
    ]
