# Generated by Django 2.0.3 on 2018-03-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cidade', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cidades',
            field=models.ManyToManyField(to='Cidade.Cidade'),
        ),
    ]
