# Generated by Django 2.0.4 on 2018-04-29 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0001_initial'),
        ('Usuario', '0002_usuario_cidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Categoria.Categoria'),
        ),
    ]
